section 3/examples/lecture3/budget/urls.py
from django.urls import path

from . import views

app_name = "budget"
urlpatterns = [
    path("", views.index, name="index"),
    path("add-category", views.add, name="add"),

    
]


# path("wiki/<str:title>", views.entry, name="entry"),

section 3/examples/lecture3/hello/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index1, name="index"),
    path("greet/<str:name>", views.greet1, name="greet"),
    path("brian", views.brian, name="brian"),
    path("david", views.david, name="david"),
]

section 3/examples/lecture3/lecture3/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("hello/", include("hello.urls")),
    path("tasks/", include("tasks.urls")),
    path("budget/", include("budget.urls")),
    path("newyear/", include("newyear.urls")),
]

section 3/examples/lecture3/newyear/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index")
]

section 3/examples/lecture3/tasks/urls.py
from django.urls import path

from . import views

app_name = "tasks"
urlpatterns = [
    path("", views.index, name="index"),
    path("add", views.add, name="add"),
]

section 3/examples/lecture3/budget/models.py
from django.db import models

# Create your models here.

section 3/examples/lecture3/hello/models.py
from django.db import models

# Create your models here.

section 3/examples/lecture3/newyear/models.py
from django.db import models

# Create your models here.

section 3/examples/lecture3/tasks/models.py
from django.db import models

# Create your models here.

section 3/examples/lecture3/budget/views.py
from django import forms
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
import markdown2


class NewCategoryForm(forms.Form):
    category = forms.CharField(label="New Category", required=True)
    allowance = forms.IntegerField(
        label="Allowance",  min_value=1, max_value=1000)


# Create your views here.
def index(request):
    y = function_to_mulitply(5)

    if "categories" not in request.session:
        request.session["categories"] = []

    # comment blah
    y = function_to_mulitply(5)

    md_string = "`Hello Section`"
    html_string = markdown2.markdown(md_string)

    return render(request, "budget/index.html",
                  {"categories": request.session["categories"],
                   "hello_html_string": html_string})


def function_to_mulitply(x):
    x *= 2
    return x


def add(request):
    """ this functino does abc... """
    # count = 1

    if request.method == "POST":
        # Fetch the form ...
        form = NewCategoryForm(request.POST)

        # Validation form and saving the budget cate
        if form.is_valid():
            category = form.cleaned_data["category"]

            print(form.cleaned_data["category"])
            print(form.cleaned_data["allowance"])

            request.session["categories"] += [category]
            # count += 1
            # my_greeting = "Hello"

            # return render(request, "budget/index.html", {}) not good

            return HttpResponseRedirect(reverse("budget:index"))

        return render(request, "budget/add.html", {
            "form": form
        })

    return render(request, "budget/add.html", {
        "form": NewCategoryForm()
    })

# '/wiki/add/<str:title>'
# '/wiki/edit/<str:title>'


# '/wiki/<str:title>'
# '/wiki/<str:title>/edit'

# '/random'

# #No good:
# '/<str:title>'


#
# def entry(request, title):
#     # print(title)
#     # pull file
#     # make into html
#     # render

section 3/examples/lecture3/hello/views.py
from django.http import HttpResponse
from django.shortcuts import render

def index0(request):
    return HttpResponse("Hello, world!")

def index1(request):
    return render(request, "hello/index.html")

def brian(request):
    return HttpResponse("Hello, Brian!")

def david(request):
    return HttpResponse("Hello, David!")

def greet0(request, name):
    return HttpResponse(f"Hello, {name.capitalize()}!")

def greet1(request, name):
    return render(request, "hello/greet.html", {
        "name": name.capitalize()
    })

section 3/examples/lecture3/newyear/views.py
import datetime

from django.shortcuts import render

# Create your views here.
def index(request):
    now = datetime.datetime.now()
    return render(request, "newyear/index.html", {
        "newyear": now.month == 1 and now.day == 1
    })

section 3/examples/lecture3/tasks/views.py
from django import forms
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

class NewTaskForm(forms.Form):
    task = forms.CharField(label="New Task")
    # priority = forms.IntegerField(label="Priority", min_value=1, max_value=5)

# Create your views here.
def index(request):
    if "tasks" not in request.session:
        request.session["tasks"] = []
    return render(request, "tasks/index.html", {
        "tasks": request.session["tasks"]
    })

def add(request):
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            task = form.cleaned_data["task"]
            request.session["tasks"] += [task]
            return HttpResponseRedirect(reverse("tasks:index"))
        else:
            return render(request, "tasks/add.html", {
                "form": form
            })
    else:
        return render(request, "tasks/add.html", {
            "form": NewTaskForm()
        })

section 3/examples/lecture3/budget/templates/budget/add.html
{% extends "budget/layout.html" %}

{% block body %}
    <h1>Add Category</h1>

    <form action="{% url 'budget:add' %}" method="post"> 
        {% csrf_token %}
        {{ form }}
        <input type="submit">
    </form>
    <a href="{% url 'budget:index' %}">View All Tasks</a>  try to comment me out? lol
    
{% endblock %}

section 3/examples/lecture3/budget/templates/budget/index.html
{% extends "budget/layout.html" %}
{% block body %}
    <h1>Categories</h1>
    <ul>
        {% for category in categories %}
            <li>{{ category }}</li>
        {% empty %}
            <li>No categories.</li>
        {% endfor %}
    </ul>


    {% comment %}{% endcomment %}

    <a href="{% url 'budget:add' %}">Add New Categories</a>  */

    <br/><br/><br/>

    {{ hello_html_string | safe }}

{% endblock %}

section 3/examples/lecture3/budget/templates/budget/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Categories</title>
    </head>
    
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>

section 3/examples/lecture3/hello/templates/hello/greet.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Hello!</title>
    </head>
    <body>
        Hello, {{ name }}!
    </body>
</html>

section 3/examples/lecture3/hello/templates/hello/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Hello!</title>
    </head>
    <body>
        Hello, world!
    </body>
</html>

section 3/examples/lecture3/newyear/templates/newyear/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Is It New Year's?</title>
        <link href="{% static 'newyear/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        {% if newyear %}
            <h1>YES</h1>
        {% else %}
            <h1>NO</h1>
        {% endif %}
    </body>
</html>

section 3/examples/lecture3/tasks/templates/tasks/add.html
{% extends "tasks/layout.html" %}

{% block body %}
    <h1>Add Task</h1>
    <form action="{% url 'tasks:add' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit">
    </form>
    <a href="{% url 'tasks:index' %}">View All Tasks</a>
{% endblock %}

section 3/examples/lecture3/tasks/templates/tasks/index.html
{% extends "tasks/layout.html" %}

{% block body %}
    <h1>Tasks</h1>
    <ul>
        {% for task in tasks %}
            <li>{{ task }}</li>
        {% empty %}
            <li>No tasks.</li>
        {% endfor %}
    </ul>
    <a href="{% url 'tasks:add' %}">Add New Task</a>
{% endblock %}

section 3/examples/lecture3/tasks/templates/tasks/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Tasks</title>
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>